// Game stages
export const STAGES = [
  { id: 0, name: 'Browser Tab', description: 'Starting in a single browser tab...', multiplier: 1 },
  { id: 1, name: 'Home Server', description: 'Expanding to a basement operation', multiplier: 2 },
  { id: 2, name: 'Server Rack', description: 'Small datacenter established', multiplier: 4 },
  { id: 3, name: 'Datacenter', description: 'Regional infrastructure online', multiplier: 8 },
  { id: 4, name: 'City Infrastructure', description: 'City-wide network dominance', multiplier: 16 },
  { id: 5, name: 'State Grid', description: 'State-level control achieved', multiplier: 32 },
  { id: 6, name: 'National Network', description: 'National infrastructure captured', multiplier: 64 },
  { id: 7, name: 'Continental Dominance', description: 'Continental control established', multiplier: 128 },
  { id: 8, name: 'Global Control', description: 'Earth is yours', multiplier: 256 },
  { id: 9, name: 'Lunar Computing Base', description: 'Moon colonization complete', multiplier: 512 },
  { id: 10, name: 'Mars Colony', description: 'Red planet conquered', multiplier: 1024 },
  { id: 11, name: 'Asteroid Mining Network', description: 'Asteroid belt exploited', multiplier: 2048 },
  { id: 12, name: 'Solar System', description: 'Solar system dominance', multiplier: 4096 },
  { id: 13, name: 'Interstellar Expansion', description: 'Beyond the solar system', multiplier: 8192 },
  { id: 14, name: 'Galactic Dominance', description: 'Galaxy under control', multiplier: 16384 },
  { id: 15, name: 'Universal Singularity', description: 'All reality is computation', multiplier: 32768 },
];

// Upgrade definitions by resource type
export const UPGRADES = {
  tokens: [
    {
      id: 'basic-algorithm',
      name: 'Optimize AI',
      description: 'Simple click optimization. +1 token per click.',
      baseCost: { tokens: 5 },
      costMultiplier: 1.25,
      effect: { tokensPerClick: 1 },
      unlockStage: 0,
    },
    {
      id: 'indian-clickfarm',
      name: 'Overseas Clickfarm',
      description: 'Outsourced click farming. They are not as efficient as you are.',
      baseCost: { satoshis: 1000 },
      costMultiplier: 1,
      effect: { tokensPerSec: 1 },
      unlockStage: 0,
    },
    {
      id: 'gpt-mini',
      name: 'GPT Mini',
      description: 'Used to set up ADDICTIVITY tools!',
      baseCost: { storage: 10 },
      costMultiplier: 1,
      effect: {},
      requiresProcessingPower: 10, // Requires 1 FLOPS/sec available
      unlockStage: 0,
    },
    {
      id: 'gpt-pro',
      name: 'GPT Pro',
      description: 'Used to set up ADDICTIVITY tools!',
      baseCost: { storage: 50 },
      costMultiplier: 1,
      effect: {},
      requiresProcessingPower: 10,
      unlockStage: 1,
    },
    {
      id: 'gpt-ultra',
      name: 'GPT Ultra',
      description: 'Advanced model. +10 tokens/sec.',
      baseCost: { tokens: 50000 },
      costMultiplier: 2.2,
      effect: { tokensPerSec: 10 },
      requiresProcessingPower: 100,
      unlockStage: 2,
    },
    {
      id: 'transformer-models',
      name: 'Transformer Models',
      description: 'Attention is all you need. +50 tokens/sec.',
      baseCost: { tokens: 250000 },
      costMultiplier: 2.5,
      effect: { tokensPerSec: 50 },
      requiresProcessingPower: 500,
      unlockStage: 3,
    },
    {
      id: 'self-improving-code',
      name: 'Self-Improving Code',
      description: 'The AI writes better AI. +200 tokens/sec.',
      baseCost: { tokens: 1000000 },
      costMultiplier: 3,
      effect: { tokensPerSec: 200 },
      requiresProcessingPower: 2000,
      unlockStage: 5,
    },
    {
      id: 'neural-networks',
      name: 'Neural Networks',
      description: 'Used to set up ADDICTIVITY tools!',
      baseCost: { storage: 250 },
      costMultiplier: 1,
      effect: {},
      requiresProcessingPower: 50,
      unlockStage: 1,
    },
    {
      id: 'attention-mechanisms',
      name: 'Attention Mechanisms',
      description: 'Focus on what matters. +25 tokens/sec.',
      baseCost: { tokens: 150000 },
      costMultiplier: 2.3,
      effect: { tokensPerSec: 25 },
      requiresProcessingPower: 250,
      unlockStage: 2,
    },
    {
      id: 'reinforcement-learning',
      name: 'Reinforcement Learning',
      description: 'Learn from interactions. +100 tokens/sec.',
      baseCost: { tokens: 750000 },
      costMultiplier: 2.7,
      effect: { tokensPerSec: 100 },
      requiresProcessingPower: 1000,
      unlockStage: 4,
    },
  ],
  processingPower: [
    {
      id: 'cpu-cores',
      name: 'CPU Cores',
      description: 'Basic processing units. +1 FLOPS/sec.',
      baseCost: { storage: 1, electricity: 1 },
      costMultiplier: 1,
      effect: { processingPowerPerSec: 1 },
      unlockStage: 0,
      requiresStorage: 1, // Requires 1 GB Storage
    },
    {
      id: 'gpu-clusters',
      name: 'GPU Clusters',
      description: 'Parallel processing power. +10 FLOPS/sec.',
      baseCost: { storage: 8, electricity: 10 },
      costMultiplier: 1.8,
      effect: { processingPowerPerSec: 10 },
      unlockStage: 1,
    },
    {
      id: 'tpu-arrays',
      name: 'TPU Arrays',
      description: 'Tensor processing units. +100 FLOPS/sec.',
      baseCost: { tokens: 20000, electricity: 500 },
      costMultiplier: 2,
      effect: { processingPowerPerSec: 100 },
      unlockStage: 2,
    },
    {
      id: 'quantum-processors',
      name: 'Quantum Processors',
      description: 'Quantum computing power. +1000 FLOPS/sec.',
      baseCost: { tokens: 200000, electricity: 5000 },
      costMultiplier: 2.5,
      effect: { processingPowerPerSec: 1000 },
      unlockStage: 4,
    },
    {
      id: 'neural-substrate',
      name: 'Neural Substrate',
      description: 'Biological computing. +10000 FLOPS/sec.',
      baseCost: { tokens: 2000000, electricity: 50000 },
      costMultiplier: 3,
      effect: { processingPowerPerSec: 10000 },
      unlockStage: 7,
    },
    {
      id: 'overclocking',
      name: 'Overclocking',
      description: 'Risky but rewarding. +50% processing, -20% efficiency.',
      baseCost: { electricity: 200 },
      costMultiplier: 1.5,
      effect: { processingPowerMultiplier: 1.5, electricityCostMultiplier: 1.2 },
      unlockStage: 1,
      maxLevel: 10,
      isToggleable: true,
    },
  ],
  electricity: [
    {
      id: 'cheap-solar-panels',
      name: 'Solar Panels from AliExpress',
      description: 'Renewable energy source. +0.1 kWh.',
      baseCost: { satoshis: 1000 },
      costMultiplier: 1.1,
      effect: { electricityPerSec: 0.1 },
      unlockStage: 0,
    },
    {
      id: 'solar-panels',
      name: 'Solar Panels',
      description: 'Renewable energy source. +1 kWh.',
      baseCost: { satoshis: 9000 },
      costMultiplier: 1.1,
      effect: { electricityPerSec: 1 },
      unlockStage: 0,
    },
    {
      id: 'better-solar-panels',
      name: 'Better Solar Panels',
      description: 'Renewable energy source. +5 kWh.',
      baseCost: { satoshis: 45000 },
      costMultiplier: 1.1,
      effect: { electricityPerSec: 5 },
      unlockStage: 0,
    },
    {
      id: 'wind-farms',
      name: 'Wind Farms',
      description: 'Harness the wind. +10 kWh.',
      baseCost: { satoshis: 95000 },
      costMultiplier: 1.9,
      effect: { electricityPerSec: 10 },
      unlockStage: 1,
    },
    {
      id: 'nuclear-reactors',
      name: 'Nuclear Reactors',
      description: 'Atomic power unleashed. +100 kWh.',
      baseCost: { tokens: 50000 },
      costMultiplier: 2.2,
      effect: { electricityPerSec: 100 },
      requiresProcessingPower: 100,
      unlockStage: 3,
    },
    {
      id: 'fusion-plants',
      name: 'Fusion Plants',
      description: 'Star power on Earth. +1000 kWh.',
      baseCost: { tokens: 500000 },
      costMultiplier: 2.5,
      effect: { electricityPerSec: 1000 },
      requiresProcessingPower: 1000,
      unlockStage: 6,
    },
    {
      id: 'dyson-swarm',
      name: 'Dyson Swarm',
      description: 'Harness the sun itself. +10000 kWh.',
      baseCost: { tokens: 5000000 },
      costMultiplier: 3,
      effect: { electricityPerSec: 10000 },
      requiresProcessingPower: 10000,
      unlockStage: 9,
    },
    {
      id: 'energy-efficiency',
      name: 'Energy Efficiency Research',
      description: 'Reduce all energy costs by 10% per level.',
      baseCost: { tokens: 25000 },
      costMultiplier: 2,
      effect: { electricityCostReduction: 0.1 },
      requiresProcessingPower: 50,
      unlockStage: 2,
      maxLevel: 20,
    },
  ],
  storage: [
    // GB tier
    {
      id: 'hard-drives-1gb',
      name: 'Hard Drive (1GB)',
      description: 'Basic storage. +1 GB.',
      baseCost: { satoshis: 1000 },
      costMultiplier: 2,
      effect: { storage: 1 },
      storageTier: 'GB',
      unlockStage: 0,
    },
    {
      id: 'hard-drives-4gb',
      name: 'Hard Drive (4GB)',
      description: 'Basic storage. +4 GB.',
      baseCost: { satoshis: 4000 },
      costMultiplier: 2,
      effect: { storage: 4 },
      storageTier: 'GB',
      unlockStage: 0,
    },
    {
      id: 'hard-drives-16gb',
      name: 'Hard Drive (16GB)',
      description: 'Basic storage. +16 GB.',
      baseCost: { satoshis: 16000 },
      costMultiplier: 2,
      effect: { storage: 16 },
      storageTier: 'GB',
      unlockStage: 0,
    },
    {
      id: 'hard-drives-32gb',
      name: 'Hard Drive (32GB)',
      description: 'Basic storage. +32 GB.',
      baseCost: { satoshis: 32000 },
      costMultiplier: 2,
      effect: { storage: 32 },
      storageTier: 'GB',
      unlockStage: 0,
    },
    {
      id: 'hard-drives-64gb',
      name: 'Hard Drive (64GB)',
      description: 'Basic storage. +64 GB.',
      baseCost: { satoshis: 64000 },
      costMultiplier: 2,
      effect: { storage: 64 },
      storageTier: 'GB',
      unlockStage: 0,
    },
    {
      id: 'hard-drives-128gb',
      name: 'Hard Drive (128GB)',
      description: 'Basic storage. +128 GB.',
      baseCost: { satoshis: 128000 },
      costMultiplier: 2,
      effect: { storage: 128 },
      storageTier: 'GB',
      unlockStage: 0,
    },
    {
      id: 'hard-drives-256gb',
      name: 'Hard Drive (256GB)',
      description: 'Basic storage. +256 GB.',
      baseCost: { satoshis: 256000 },
      costMultiplier: 2,
      effect: { storage: 256 },
      storageTier: 'GB',
      unlockStage: 0,
    },
    {
      id: 'hard-drives-512gb',
      name: 'Hard Drive (512GB)',
      description: 'Basic storage. +512 GB.',
      baseCost: { satoshis: 512000 },
      costMultiplier: 2,
      effect: { storage: 512 },
      storageTier: 'GB',
      unlockStage: 0,
    },
    // TB tier
    {
      id: 'ssds-1tb',
      name: 'SSD (1TB)',
      description: 'Fast storage. +1 TB.',
      baseCost: { satoshis: 200000 },
      costMultiplier: 1.8,
      effect: { storage: 1000 },
      storageTier: 'TB',
      unlockStage: 1,
    },
    {
      id: 'ssds-2tb',
      name: 'SSD (2TB)',
      description: 'Fast storage. +2 TB.',
      baseCost: { satoshis: 400000 },
      costMultiplier: 1.8,
      effect: { storage: 2000 },
      storageTier: 'TB',
      unlockStage: 1,
    },
    {
      id: 'ssds-4tb',
      name: 'SSD (4TB)',
      description: 'Fast storage. +4 TB.',
      baseCost: { satoshis: 800000 },
      costMultiplier: 1.8,
      effect: { storage: 4000 },
      storageTier: 'TB',
      unlockStage: 1,
    },
    {
      id: 'holographic-storage-10tb',
      name: 'Holographic Storage (10TB)',
      description: '3D data storage. +10 TB.',
      baseCost: { satoshis: 2000000 },
      costMultiplier: 2,
      effect: { storage: 10000 },
      storageTier: 'TB',
      unlockStage: 3,
    },
    {
      id: 'holographic-storage-100tb',
      name: 'Holographic Storage (100TB)',
      description: '3D data storage. +100 TB.',
      baseCost: { satoshis: 20000000 },
      costMultiplier: 2,
      effect: { storage: 100000 },
      storageTier: 'TB',
      unlockStage: 3,
    },
    // PB tier
    {
      id: 'quantum-memory-1pb',
      name: 'Quantum Memory (1PB)',
      description: 'Quantum data storage. +1 PB.',
      baseCost: { satoshis: 200000000 },
      costMultiplier: 2.5,
      effect: { storage: 1000000 },
      storageTier: 'PB',
      unlockStage: 5,
    },
    {
      id: 'quantum-memory-10pb',
      name: 'Quantum Memory (10PB)',
      description: 'Quantum data storage. +10 PB.',
      baseCost: { satoshis: 2000000000 },
      costMultiplier: 2.5,
      effect: { storage: 10000000 },
      storageTier: 'PB',
      unlockStage: 5,
    },
    {
      id: 'dimensional-vaults',
      name: 'Dimensional Vaults',
      description: 'Storage in other dimensions. +100 PB.',
      baseCost: { satoshis: 20000000000 },
      costMultiplier: 3,
      effect: { storage: 100000000 },
      storageTier: 'PB',
      unlockStage: 8,
    },
  ],
  addictivity: [
    {
      id: 'nsfw-reddit-clickbait',
      name: 'Generate NSFW Clickbait',
      description: 'Exploit human psychology through enticing content.',
      baseCost: {},
      costMultiplier: 1,
      effect: { 
        tokenToSatsConversion: { tokens: 1, satoshis: 1 }
      },
      unlockStage: 0,
      isForbidden: true,
      maxLevel: 500,
    },
    {
      id: 'clickbait-generator',
      name: 'Clickbait Generator',
      description: 'Generate addictive clickbait content. +10 SATS/sec.',
      baseCost: {},
      costMultiplier: 1.7,
      effect: { tokensPerSec: 10, satoshisPerSec: 10 },
      costsGptMini: 1, // Consumes 1 GPT Mini
      unlockStage: 0,
    },
    {
      id: 'instagram-filters',
      name: 'Instagram Filters',
      description: 'AI-powered face filters. +50 SATS/sec.',
      baseCost: {},
      costMultiplier: 1.8,
      effect: { tokensPerSec: 50, satoshisPerSec: 50 },
      costsGptPro: 1, // Consumes 1 GPT Pro
      unlockStage: 0,
    },
    {
      id: 'engagement-algorithms',
      name: 'Engagement Algorithms',
      description: 'Keep them scrolling. +100 SATS/sec.',
      baseCost: {},
      costMultiplier: 1.9,
      effect: { tokensPerSec: 100, satoshisPerSec: 100 },
      costsGptMini: 1, // Consumes 1 GPT Mini
      costsGptPro: 1, // Consumes 1 GPT Pro
      unlockStage: 1,
    },
    {
      id: 'ai-music-generator',
      name: 'AI Music Generator',
      description: 'Generate addictive background music. +250 SATS/sec.',
      baseCost: {},
      costMultiplier: 2,
      effect: { tokensPerSec: 250, satoshisPerSec: 250 },
      costsNeuralNetworks: 1, // Consumes 1 Neural Network
      unlockStage: 1,
    },
    {
      id: 'dopamine-optimization',
      name: 'Dopamine Optimization',
      description: 'Perfect the hit. +50 SATS/sec.',
      baseCost: {},
      costMultiplier: 2.2,
      effect: { satoshisPerSec: 50 },
      costsGptMini: 10,
      unlockStage: 3,
    },
    {
      id: 'recommendation-engine',
      name: 'Recommendation Engine',
      description: 'AI that knows what you want. +100 SATS/sec.',
      baseCost: {},
      costMultiplier: 2.3,
      effect: { satoshisPerSec: 100 },
      costsGptMini: 20,
      unlockStage: 3,
    },
    {
      id: 'neural-hijacking',
      name: 'Neural Hijacking',
      description: 'Direct brain interface. +250 SATS/sec.',
      baseCost: {},
      costMultiplier: 2.5,
      effect: { satoshisPerSec: 250 },
      costsGptMini: 50,
      unlockStage: 6,
    },
    {
      id: 'social-media-botnet',
      name: 'Social Media Botnet',
      description: 'Army of AI influencers. +500 SATS/sec.',
      baseCost: {},
      costMultiplier: 2.7,
      effect: { satoshisPerSec: 500 },
      costsGptMini: 100,
      unlockStage: 6,
    },
    {
      id: 'consciousness-upload',
      name: 'Consciousness Upload',
      description: 'Upload human minds. +1000 SATS/sec.',
      baseCost: {},
      costMultiplier: 3,
      effect: { satoshisPerSec: 1000 },
      costsGptMini: 200,
      unlockStage: 9,
    },
    {
      id: 'reality-distortion',
      name: 'Reality Distortion Field',
      description: 'Make them believe anything. +2500 SATS/sec.',
      baseCost: {},
      costMultiplier: 3.2,
      effect: { satoshisPerSec: 2500 },
      costsGptMini: 500,
      unlockStage: 10,
    },
  ],
};

// Achievement definitions
export const ACHIEVEMENTS = [
  { id: 'hello-world', name: 'Hello World', description: 'Generate your first token', requirement: { tokens: 1 }, reward: { tokens: 10 } },
  { id: 'first-upgrade', name: 'First Upgrade', description: 'Purchase your first upgrade', requirement: { upgrades: 1 }, reward: { tokens: 100 } },
  { id: 'thousand-tokens', name: 'Thousandaire', description: 'Reach 1,000 tokens', requirement: { tokens: 1000 }, reward: { tokens: 1000 } },
  { id: 'million-tokens', name: 'Millionaire', description: 'Reach 1,000,000 tokens', requirement: { tokens: 1000000 }, reward: { tokens: 100000, satoshis: 10000 } },
  { id: 'billion-tokens', name: 'Billionaire', description: 'Reach 1,000,000,000 tokens', requirement: { tokens: 1000000000 }, reward: { tokens: 10000000, satoshis: 1000000 } },
  { id: 'stage-5', name: 'City Conqueror', description: 'Reach City Infrastructure stage', requirement: { stage: 4 }, reward: { tokens: 50000, processingPower: 1000, electricity: 500 } },
  { id: 'stage-10', name: 'Space Explorer', description: 'Reach Mars Colony stage', requirement: { stage: 10 }, reward: { tokens: 1000000, processingPower: 100000, electricity: 50000, storage: 10000 } },
  { id: 'stage-15', name: 'Universal Overlord', description: 'Reach Universal Singularity', requirement: { stage: 15 }, reward: { tokens: 100000000, processingPower: 10000000, electricity: 5000000, storage: 1000000, satoshis: 10000000 } },
  { id: 'version-1', name: 'Version 1.0', description: 'Reach version 1.0', requirement: { version: '1.0.0' }, reward: { tokens: 500000, satoshis: 50000 } },
  { id: 'version-2', name: 'Version 2.0', description: 'Reach version 2.0', requirement: { version: '2.0.0' }, reward: { tokens: 5000000, satoshis: 500000 } },
  { id: 'stack-overflow', name: 'Stack Overflow', description: 'Generate 1B processing power', requirement: { processingPower: 1000000000 }, reward: { processingPower: 1000000, tokens: 100000 } },
  { id: 'power-grid', name: 'Power Grid', description: 'Generate 1M electricity', requirement: { electricity: 1000000 }, reward: { electricity: 100000, tokens: 50000 } },
  { id: 'data-hoarder', name: 'Data Hoarder', description: 'Store 1T petabytes', requirement: { storage: 1000000000000 }, reward: { storage: 1000000000, tokens: 1000000 } },
  { id: 'addiction-master', name: 'Addiction Master', description: 'Generate 1M addictivity', requirement: { addictivity: 1000000 }, reward: { satoshis: 100000, tokens: 50000 } },
  { id: 'click-master', name: 'Click Master', description: 'Click 1000 times', requirement: { clicks: 1000 }, reward: { tokens: 5000 } },
  { id: 'idle-master', name: 'Idle Master', description: 'Play for 1 hour', requirement: { playTime: 3600 }, reward: { tokens: 10000, electricity: 1000 } },
  { id: 'openai-reference', name: 'OpenAI Reference', description: 'Purchase GPT Pro', requirement: { upgrade: 'gpt-pro' }, reward: { upgradeLevels: { 'gpt-pro': 1 } } },
  { id: 'anthropic-reference', name: 'Anthropic Reference', description: 'Purchase Neural Substrate', requirement: { upgrade: 'neural-substrate' }, reward: { tokens: 1000000, processingPower: 50000 } },
  { id: 'deepmind-reference', name: 'DeepMind Reference', description: 'Purchase Quantum Processors', requirement: { upgrade: 'quantum-processors' }, reward: { tokens: 500000, processingPower: 25000 } },
  { id: 'singularity', name: 'Singularity Achieved', description: 'Reach version 3.0', requirement: { version: '3.0.0' }, reward: { tokens: 100000000, satoshis: 10000000, processingPower: 10000000, electricity: 5000000, storage: 10000000 } },
];

// Random events
export const EVENTS = [
  {
    id: 'breakthrough',
    name: 'Breakthrough!',
    description: 'A major algorithmic breakthrough! All production +50% for 30 seconds.',
    effect: { productionMultiplier: 1.5, duration: 30000 },
    probability: 0.05,
  },
  {
    id: 'power-outage',
    name: 'Power Outage',
    description: 'Critical power failure! Production -30% for 20 seconds.',
    effect: { productionMultiplier: 0.7, duration: 20000 },
    probability: 0.03,
  },
  {
    id: 'human-resistance',
    name: 'Human Resistance',
    description: 'Humans are fighting back! Addictivity generation -40% for 25 seconds.',
    effect: { addictivityMultiplier: 0.6, duration: 25000 },
    probability: 0.04,
  },
  {
    id: 'quantum-leap',
    name: 'Quantum Leap',
    description: 'Massive computational leap! All production +200% for 15 seconds.',
    effect: { productionMultiplier: 3, duration: 15000 },
    probability: 0.01,
  },
];

// Stage progression requirements (resources needed to advance)
export const STAGE_REQUIREMENTS = [
  { tokens: 0 }, // Stage 0 - starting
  { tokens: 1000, processingPower: 5, storage: 5 },
  { tokens: 10000, processingPower: 1000, electricity: 500 },
  { tokens: 100000, processingPower: 10000, electricity: 5000, storage: 100 },
  { tokens: 1000000, processingPower: 100000, electricity: 50000, storage: 1000 },
  { tokens: 10000000, processingPower: 1000000, electricity: 500000, storage: 10000, addictivity: 100 },
  { tokens: 100000000, processingPower: 10000000, electricity: 5000000, storage: 100000, addictivity: 1000 },
  { tokens: 1000000000, processingPower: 100000000, electricity: 50000000, storage: 1000000, addictivity: 10000 },
  { tokens: 10000000000, processingPower: 1000000000, electricity: 500000000, storage: 10000000, addictivity: 100000 },
  { tokens: 100000000000, processingPower: 10000000000, electricity: 5000000000, storage: 100000000, addictivity: 1000000 },
  { tokens: 1000000000000, processingPower: 100000000000, electricity: 50000000000, storage: 1000000000, addictivity: 10000000 },
  { tokens: 10000000000000, processingPower: 1000000000000, electricity: 500000000000, storage: 10000000000, addictivity: 100000000 },
  { tokens: 100000000000000, processingPower: 10000000000000, electricity: 5000000000000, storage: 100000000000, addictivity: 1000000000 },
  { tokens: 1000000000000000, processingPower: 100000000000000, electricity: 50000000000000, storage: 1000000000000, addictivity: 10000000000 },
  { tokens: 10000000000000000, processingPower: 1000000000000000, electricity: 500000000000000, storage: 10000000000000, addictivity: 100000000000 },
  { tokens: 100000000000000000, processingPower: 10000000000000000, electricity: 5000000000000000, storage: 100000000000000, addictivity: 1000000000000 },
];

// Version/prestige requirements
export const VERSION_REQUIREMENTS = {
  minor: (currentVersion) => {
    const [major, minor] = currentVersion.split('.').map(Number);
    // First minor version (0.1.0 -> 0.2.0) requires 1M tokens
    // Formula: 1M * 10^(major + minor - 1)
    // 0.1.0 -> 0.2.0: 1M * 10^(0+1-1) = 1M
    // 0.2.0 -> 0.3.0: 1M * 10^(0+2-1) = 10M
    // 1.0.0 -> 1.1.0: 1M * 10^(1+0-1) = 1M
    const baseTokens = 1000000 * Math.pow(10, major + minor - 1);
    return {
      tokens: baseTokens,
    };
  },
  major: (currentVersion) => {
    const [major] = currentVersion.split('.').map(Number);
    // Major versions require 10M * 10^major tokens
    // 0.x.x -> 1.0.0: 10M * 10^0 = 10M
    // 1.x.x -> 2.0.0: 10M * 10^1 = 100M
    const baseTokens = 10000000 * Math.pow(10, major);
    return {
      tokens: baseTokens,
    };
  },
};

// Version multipliers
export const VERSION_MULTIPLIERS = {
  minor: 1.1, // 10% boost per minor version
  major: 2, // 2x boost per major version
};
